import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import { ReactNode } from 'react';
import { Header } from '@/widgets/Header';
import { StoreProvider } from '@/app/store';
import { AdWidget } from '@/widgets/Ad';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const adsData = [
  {
    image: 'https://via.placeholder.com/150x300',
    link: 'https://example.com/product1',
    alt: 'Product 1',
  },
  {
    image: 'https://via.placeholder.com/150x300',
    link: 'https://example.com/product2',
    alt: 'Product 2',
  },
];

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="layout-container">
        <div className="ad-widget-left">
          <AdWidget ads={adsData} />
        </div>

        <div className="content-container">
          <Header />
          {children}
        </div>

        <div className="ad-widget-right">
          <AdWidget ads={adsData} />
        </div>
      </div>
      </body>
      </html>
    </StoreProvider>
  );
}
