import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import { ReactNode } from 'react';
import { Header } from '@/widgets/Header';
import { StoreProvider } from '@/app/store';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <div style={{ width: '200px' }}> {/* Реклама слева */}
          Реклама слева
        </div>

        <div className="container" style={{ flex: 1 }}>
          <Header />
          {children}
        </div>

        <div style={{ width: '200px' }}> {/* Реклама справа */}
          Реклама справа
        </div>
      </div>


      </body>
      </html>
    </StoreProvider>
  );
}
